"""empty message

Revision ID: 7940f7cacd5e
Revises: 
Create Date: 2020-04-30 12:19:11.449444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7940f7cacd5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=100), nullable=True),
    sa.Column('fantasyname', sa.String(length=100), nullable=True),
    sa.Column('rubro', sa.String(length=100), nullable=True),
    sa.Column('empleados', sa.String(length=100), nullable=True),
    sa.Column('ingresos', sa.String(length=100), nullable=True),
    sa.Column('file', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('visit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visit')
    op.drop_table('users')
    # ### end Alembic commands ###
